export const JUEGO = {
  VIDAS_INICIALES: 3,
  PUNTOS_GOOMBA: 100,
  PUNTOS_KOOPA: 200,
  PUNTOS_MONEDA: 50,
  PUNTOS_BLOQUE: 50,
  PUNTOS_HONGO: 100,
  MONEDAS_VIDA_EXTRA: 100,
  DURACION_INVENCIBLE: 2000, // ms
} as const;
